views/player.py
from flask import abort, Blueprint, redirect, render_template, url_for, flash
from flask_login import current_user

from forms import NewPlayerSessionForm
from models import PlayerSession

blueprint = Blueprint('player', __name__, template_folder='templates')


@blueprint.route('/new', methods=['GET', 'POST'])
def new():
    new_player_session_form = NewPlayerSessionForm()
    if not current_user.is_authenticated:
        new_player_session_form.moderated.render_kw = {'disabled': ''}
    if new_player_session_form.validate_on_submit():
        player_session = PlayerSession.create(
            owner_id=current_user.id if current_user.is_authenticated else None,
            video_url=new_player_session_form.video_url.data,
            moderated=new_player_session_form.moderated.data,
        )
        return redirect(url_for('.player', token=player_session.token))
    return render_template('player/new.html', new_player_session_form=new_player_session_form)


@blueprint.route('/<string:token>')
def player(token: str):
    player_session = PlayerSession.get_by_token(token)
    if not player_session:
        abort(404)
    return render_template('player/player.html', player_session=player_session)

views/users.py
from datetime import datetime, timedelta

import requests
from flask import abort, Blueprint, render_template, redirect, url_for, send_file, request
from flask import current_app as app
from flask_login import current_user, login_required, login_user, logout_user

import config
from forms import LoginForm, RegisterForm, PasswordForgotForm, PasswordResetForm
from models import db, PasswordResetToken
from models import login_manager, User

login_manager.login_view = '/login'

blueprint = Blueprint('users', __name__, template_folder='templates')


@blueprint.route('/login', methods=['GET', 'POST'])
def login():
    login_form = LoginForm()
    if login_form.validate_on_submit():
        login_user(login_form.get_user())
        return redirect(url_for('.profile'))
    return render_template('users/login.html', login_form=login_form)


@blueprint.route('/register', methods=['GET', 'POST'])
def register():
    register_form = RegisterForm()
    if register_form.validate_on_submit():
        new_user = User()
        register_form.populate_obj(new_user)
        db.session.add(new_user)
        db.session.commit()
        login_user(new_user)
        return redirect(url_for('.profile'))
    return render_template('users/register.html', register_form=register_form)


@blueprint.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('base.index'))


# TODO: implement user avatars
@blueprint.route('/avatar/<int:user_id>')
def user_avatar(user_id):
    return send_file('static/images/user.jpg')


@blueprint.route('/password/forgot', methods=['GET', 'POST'])
def user_password_forgot():
    forgot_form = PasswordForgotForm()
    if forgot_form.validate_on_submit():
        if forgot_form.user is not None:
            token = PasswordResetToken(
                active=True,
                user=forgot_form.user,
                email=forgot_form.email.data,
                expire=datetime.now() + timedelta(days=1),
            )
            db.session.add(token)
            db.session.commit()
            url = 'http://%s/password/reset/%s' % (request.host, token.token)
            requests.post('https://api.mailgun.net/v3/%s/messages' % app.config['MAILGUN_DOMAIN'],
                          auth=('api', app.config['MAILGUN_API_KEY']), data={
                    'from': 'CTF Calendar Admin <team@easyctf.com>',
                    'to': forgot_form.email.data,
                    'subject': 'CTF Calendar Password Reset',
                    'html': 'Click here to reset your password: <a href="%s">%s</a>' % (url, url)
                })
        return render_template('users/forgot.html', check_your_email=True)
    return render_template('users/forgot.html', forgot_form=forgot_form)


@blueprint.route('/password/reset/<string:code>', methods=['GET', 'POST'])
def user_password_reset(code):
    token = PasswordResetToken.query.filter_by(token=code, active=True).first()
    if not token or token.expired or token.email != token.user.email:
        abort(404)

    reset_form = PasswordResetForm()
    if reset_form.validate_on_submit():
        user = token.user
        user.password = reset_form.password.data
        token.active = False
        db.session.commit()
        return render_template('users/reset.html', password_reset=True)
    return render_template('users/reset.html', reset_form=reset_form)


@blueprint.route('/profile', methods=['GET'])
@login_required
def profile():
    return redirect(url_for('.users_detail', user_id=current_user.id))


# @blueprint.route('/users')
# @blueprint.route('/users/page/<int:page_number>')
def users_list(page_number=1):
    if page_number <= 0:
        abort(404)

    page_size = config.USER_LIST_PAGE_SIZE
    page_offset = (page_number - 1) * page_size
    users = User.query.order_by(User.id).order_by(User.id.desc()).offset(page_offset).limit(page_size + 1).all()
    if page_number != 1 and not users:
        abort(404)

    last_page = len(users) <= page_size
    if not last_page:
        users.pop()

    return render_template('users/list.html', page_number=page_number, last_page=last_page, users=users)


@blueprint.route('/users/<int:user_id>')
def users_detail(user_id):
    user = User.query.get_or_404(user_id)
    return render_template('users/profile.html', user=user)

templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>

    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet"
          integrity="sha384-T8Gy5hrqNKT+hzMclPo118YTQO6cYprQmhrYwIiQ/3axmI1hQomh7Ud2hPOy8SP1" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-2.1.4.min.js"
            integrity="sha384-R4/ztc4ZlRqWjqIuvf6RX5yb/v90qNGx6fS48N0tRxiGkqveZETq72KgDVJCp2TC"
            crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"
            integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS"
            crossorigin="anonymous"></script>

    {% block head %}{% endblock %}
</head>
<body>
<nav role="navigation" class="navbar navbar-inverse">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-content"
                    aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">VideoSync</a>
        </div>
        <div id="navbar-content" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li><a href="{{ url_for('player.new') }}">New Player</a></li>
                <li class="dropdown">
                    <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button"
                       aria-haspopup="true" aria-expanded="false">Foobar <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Foo</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#">Bar</a></li>
                    </ul>
                </li>
                <li><a href="#">About</a></li>
            </ul>
            {% if current_user.is_authenticated %}
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button"
                           aria-haspopup="true" aria-expanded="false">{{ current_user.username }} <span
                                class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="{{ url_for('users.profile') }}">Profile</a></li>
                            <li><a href="{{ url_for('users.logout') }}">Logout</a></li>
                        </ul>
                    </li>
                </ul>
            {% else %}
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{{ url_for('users.register') }}">Register</a></li>
                    <li><a href="{{ url_for('users.login') }}">Login</a></li>
                </ul>
            {% endif %}
        </div>
    </div>
</nav>

<div class="container">
    {% with messages = get_flashed_messages() %}
        {% if messages %}
            <div class="alert alert-info">
                <ul class=flashes>
                    {% for message in messages %}
                        <li>{{ message }}</li>
                    {% endfor %}
                </ul>
            </div>
        {% endif %}
    {% endwith %}
    {% block content %}{% endblock %}
</div>
</body>
</html>